version: "3"

services:

  database: 
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=typeormexample

  app:
    build: 
      context: .
    ports:
      - 8080:3000
    entrypoint: wait-for database:3306 -t 40 -- sh -c "npm install & npm start" 
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
